### ISSUE TITLE
Some cell formatting not working

### ISSUE THREAD

**Issue by shaggycamel** [posit-dev/great-tables#114]
## Description

The text colour and cell border from tab_style aren't working as expected.
The below code should produce a table that has yellow cell borders, and green or red text in the `Risk` column.

Somehow, the text colour condition is only being applied to the first row, and incorrectly (ie, the condition isn't being met properly). And, the cell border command isn't firing.

## Reproducible example

```
import pandas as pd
import great_tables as gt

df_risk = pd.DataFrame({
    'Activity': ['Project Management', 'Forward Works Programme', 'Database Services', 'Condition Data Collection', 'Technical Support'],
    'Risk': [1,2,3,1,1]
})

(gt.GT(df_risk)
.tab_style(style=[gt.style.fill(color='white'), gt.style.borders(color='yellow')], locations=gt.loc.body())
.tab_style(style=gt.style.text(color='black'), locations=gt.loc.body(columns='Activity'))
.tab_style(style=gt.style.text(color='green'), locations=gt.loc.body(columns='Risk', rows='Risk'==1))
.tab_style(style=gt.style.text(color='red'), locations=gt.loc.body(columns='Risk', rows=('Risk'==2 or 'Risk'==3)))
.tab_options(column_labels_hidden=True))

```

This is producing a table that looks like this. - No cell borders and incorrect text colour formatting.

![image](https://github.com/posit-dev/great-tables/assets/30674501/f4e34c52-d91b-454e-8293-27267221deed)

## Development environment

- Operating System: Windows
- Python Version: 3.11.7
- **great_tables** Version: 0.1.5

**Comment by machow** [comment]
Statements like `"Risk" == 2` return False, since the string "Risk" is not equal to 2. The lambda tells Great Tables it's a function for filtering rows based on the data.

See https://posit-dev.github.io/great-tables/get-started/basic-styling.html#using-a-function

**Comment by shaggycamel** [comment]
Yes, that works. Thank you! - Although, that still leaves the border formatting. How does one apply colour formatting to all table borders?

Another question (I'm an R user using Python for work): what is the Python syntax to use an `or` condition within a lambda function? (my example used this `rows=('Risk'==2 or 'Risk'==3)` albeit, sans lambda)

**Comment by machow** [comment]
Python is a bit funky, in that data tools override `|` to be or, but the rhs and lhs need to be in parentheses:

```
lambda df: (df["Risk"] == 2) | (df["Risk"] == 3)
```

Alternatively, you could use the pandas Series .isin() method. Hope this helps!

**Comment by shaggycamel** [comment]
Thanks @machow, works a charm. I'm looking forward to using python::gt more.

**Comment by rich-iannone** [comment]
@shaggycamel regarding the question of applying formatting to all table borders, we cannot yet do that in Great Tables. It's on the roadmap though!
