### ISSUE TITLE
Allow display of images `fmt_image()`

### ISSUE THREAD

**Issue by machow** [posit-dev/great-tables#156]
It would be neat to recreate [this table from twitter](https://twitter.com/LisaHornung_/status/1752981867769266231?s=20):

![image](https://github.com/posit-dev/great-tables/assets/2574498/8481c24b-5c6b-48ad-afab-1dc39a090b67)

I wonder if one thing necessary for displaying the icons would be implementing `fmt_image()`? Alternatively, it seems like we could manually use html for each icon cell?

**Comment by rich-iannone** [comment]
Yeah! Having a `fmt_image()` function would make this possible. We could also use `fmt_markdown()` which should pass through HTML/SVG.
