### ISSUE TITLE
Blog post on `tab_options()`

### ISSUE THREAD

**Issue by machow** [posit-dev/great-tables#179]
@rich-iannone is cooking on it!

**Comment by machow** [comment]
I'll write up a guide entry for tab_options. We can point to it from a release post. And then can always focus on a story about using tab_options for theming in a week or so.

**Comment by machow** [comment]
Let's call this done once the guide is up, and then revisit a theming post later.

**Comment by rich-iannone** [comment]
From pairing we decided, guide page is sufficient for this.
