### ISSUE TITLE
epic: Implement `sub_*()` functions

### ISSUE THREAD

**Issue by machow** [posit-dev/great-tables#182]
Functions like `sub_missing()` and `sub_zero()` allow you to replace specific values in the table. Replacing missing is especially useful, so it isn't left blank (or rendered as None).

**Comment by machow** [comment]
Related to #134, we should decide on the default representation of missing values (e.g. in pandas it's currently blank, in polars it shows None).

**Comment by rich-iannone** [comment]
I'm kinda leaning toward having something visible so that users really know that there are missing values that require some finalizing action. Currently I think `"None"` is better than `""`, so we could improve things by making the Pandas missing be `"None"`. We could go further and choose something like `"NA"` (like R) or `"N/A"` (like Excel) but I'm totally good with just harmonizing on `"None"`.

**Comment by machow** [comment]
That makes sense! I could even see leaving the string representation of w/e the null value we received for pandas was (e.g. pd.NA, None, np.nan), so people know what they put in.

One trick for us to consider is that pandas considers np.nan a null, while [polars considers it an nan](https://docs.pola.rs/user-guide/expressions/null/#null-and-nan-values).

```python
import pandas as pd
import polars as pl
import numpy as np

pl_ser = pl.Series([np.nan])
pd_ser = pd.Series([np.nan])

pl_ser.is_null()       # False
pd_ser.isnull()        # True

pl_ser.is_nan()        # True
```

I wonder if we should add a `sub_nan` that...

* For polars, uses `is_nan()`
* For pandas, uses `is_null()` (so that sub_nan and sub_missing do the same thing for pandas)

WDYT?

**Comment by ChristopherRussell** [comment]
I would vote on using the string rep of whatever nan/null value is present as a default: 'None', 'nan' 'NaT'. Avoids any surprises. 

Other than that, definitely want to be able to choose whether to substitute different values for nan and null in float columns.

**Comment by rich-iannone** [comment]
I think we ought to add that `sub_nan` method to the list. That way, users can make much more targeted replacements where the distinction is important.
