### ISSUE TITLE
Add roadmap (as a table) to the README

### ISSUE THREAD

**Issue by rich-iannone** [posit-dev/great-tables#188]
We need to have a way to get a roadmap generated, updated regularly (as a table), and placed in the README. This will allow us to better communicate what we're working on and what people can expect next (or later on) in terms of features and fixes.

**Comment by machow** [comment]
If it's okay, I'm going to close this. It seems like gt was able to serve its audience well without a roadmap in its README. I definitely think it's valuable to tell people what's coming down the pipe, but want to eliminate distraction (happy to re-open / discuss)
