### ISSUE TITLE
Standardizing code style for checking container emptiness

### ISSUE THREAD

**Issue by jrycw** [posit-dev/great-tables#194]
To determine whether a container-like structure is empty in Python, we typically use `if not container` or `if len(container)==0`. Both approaches are acceptable in my view. However, it seems redundant to use `if not len(container)` in the code, as seen [here](https://github.com/posit-dev/great-tables/blob/bfc9a5cf99fc0ff98f7aeb6aefa5863bdaa8e7db/great_tables/_spanners.py#L257). It would be better to simplify the code using one of the common patterns I described.

I suggest standardizing the code style for this type of check. We can use both `if not container` and `if len(container)==0`, but let's aim to replace `if not len(container)` with one of these two options.

If we can agree on this approach, I'm ready to submit a PR to address it.

**Comment by machow** [comment]
Hey, thanks for surfacing. I feel okay with how it's written, but since the next elif clause uses `len(sel_after) > 1`, I could see us changing the original check to `if len(sel_after) == 0`.

If you want to submit a PR for that, happy to merge!

**Comment by jrycw** [comment]
Thanks for the response. It seems like this issue pertains more to a preference in code style. Allow me to delve a bit deeper into my perspective.

When I encounter the code `if not container`, it's immediately clear to me that the if-statement is evaluating the container's truthiness. Conversely, when I come across if `len(container) == 0`, I understand that the if-statement is checking the container's length using the `len()` function, which relies on the return value of the `__len__()` dunder method of the container's class.

However, when I encounter `if not len(container)`, I find myself needing to first consider the length of the container and then deduce the truth value based on that number. This additional step feels a bit like a detour to me.
