### ISSUE TITLE
ability to save table to a png

### ISSUE THREAD

**Issue by bkxndata** [posit-dev/great-tables#203]
Amazing work on this project -- I'm highly appreciative

I'm curious if there is any way to save a table to a .png (or any sort of image).  I'm looking for something similar to the gtsave package in gt.  I know there's a way to render the html code, but curious if I'm missing a way to export to image.

Thank you in advance

**Comment by rich-iannone** [comment]
Use this: https://github.com/vgalin/html2image

**Comment by rich-iannone** [comment]
From Discord user `dersu` in great_tables server, this code can be adapted:

```python
from html2image import Html2Image
from IPython.core.display import HTML

html_file_path = r"C:\Scripts\test.html"

# Get the HTML content from the displayed output
html_content = HTML(gt._repr_html_()).data

# Save the HTML content to a file
with open(html_file_path, "w") as f:
    f.write(html_content)

# Instantiate Html2Image
hti = Html2Image()

# Screenshot an HTML file
hti.screenshot(
    html_file=html_file_path, save_as="test.png"
)
```

**Comment by rich-iannone** [comment]
^^^ tried this approach. Was a bit disappointed with the result. You can’t target the table element, the image is at a low resolution, and it’s uncropped. 

Another way is to use Selenium, which provides more access to the Chrome Webdriver. And you can target the table element too.

**Comment by Yasin197** [comment]
> Amazing work on this project -- I'm highly appreciative
> 
> I'm curious if there is any way to save a table to a .png (or any sort of image).  I'm looking for something similar to the gtsave package in gt.  I know there's a way to render the html code, but curious if I'm missing a way to export to image.
> 
> Thank you in advance
> 
> 

Hi, do you have an example where your concert the GT table into HTML?
