### ISSUE TITLE
great-tables==0.3.1 is not compatible with python 3.7 because of htmltools>=0.4.1 is required

### ISSUE THREAD

**Issue by Yasin197** [posit-dev/great-tables#220]
## Description
The dependency htmltools>=0.4.1 requires python version 3.8

## Expected result
Pypi states that great-tables is compatible with python 3.7

## Development environment

- Operating System: [Linux, Windows]
- **great_tables** Version: [0.3.1]

**Comment by machow** [comment]
Based on numpy NEP 29, we might consider dropping python 3.7 support. numpy dropped support around Dec 26, 2021 (a little over 2 years ago). It's tricky to support 3.7, given our dependency on the data ecosystem :/
