### ISSUE TITLE
Random table (generate & export)

### ISSUE THREAD

**Issue by AhmadHakami** [posit-dev/great-tables#223]
I'm now wondering if it is possible to add the following new features:
1. generate random tables with an `n_times` parameter
2. export the table as a json file, including bboxes for each element with the same alignment as the table & text direction to make work perfectly other languages (right to left - left to right) and (bottom to top - top to bottom)

Thanks :)

**Comment by AhmadHakami** [comment]
any updates?

**Comment by machow** [comment]
Hey @AhmadHakami, thanks for opening this issue. Do you mind saying more about what you're trying to do? What will generating random tables with an `n_times` parameter help you do?

Thanks!

**Comment by AhmadHakami** [comment]
this feature is crucial for generating essential data in developing an ocr model and it improves extraction from scanned documents especially if they contain tables also ensuring adherence to the same order/alignments of elements in the end this facilitates the improvement of comprehensive language models and tailored solutions for handling tabular information

**Comment by rich-iannone** [comment]
Sorry @AhmadHakami but this seems out of scope for what Great Tables is trying to accomplish. My suggestion is to create something that might use Great Tables in some way to get the job done.
