### ISSUE TITLE
Support non-chrome browsers in .save()

### ISSUE THREAD

**Issue by machow** [posit-dev/great-tables#227]
Currently, we require users to have Chrome in order to .save() tables as an image or pdf. Let's track here extending the `.save()` method to support other browsers. I'm not sure of the nuances that might be involved.

Here is the code that specifies Chrome specifically:

https://github.com/posit-dev/great-tables/blob/main/great_tables/_export.py#L127-L138

**Comment by rich-iannone** [comment]
Fixed with https://github.com/posit-dev/great-tables/pull/262.
