### ISSUE TITLE
Remove mentions of 'Accounting' format in docs

### ISSUE THREAD

**Issue by Yasin197** [posit-dev/great-tables#241]
In the docs it mentions numbers will be formatted if accounting=True.

So I would expect negative numbers would be represented in accounting terms e.g. a cell with value of 2 would be represented as (2)

I don't see a clean example on how to use this API?

**Comment by rich-iannone** [comment]
Thanks for reporting this. I had a look at the documentation and this appears to be a mistake. There is the repeated line:

`"This option is disregarded when using notation with 'accounting = True'"`

We don't yet have accounting notation implemented in the relevant numeric formatting methods.

I think the best course of action right now is to remove all mention of this in the docs and create an issue that tracks the implementation of accounting notation.
