### ISSUE TITLE
Spanners use 'id' as a label and not 'label'.

### ISSUE THREAD

**Issue by aussetg** [posit-dev/great-tables#273]
## Description

Spanners use 'id' as a label and not 'label', despite what the documentation says.

## Reproducible example

```python
import polars as pl
from great_tables import GT

(
    GT(
        pl.DataFrame({'a': range(5), 'b': range(5)}),
    )
    .tab_spanner(label='True Label', id='false_label', columns=['a', 'b'])
)
```

## Expected result

A spanner called 'True Label'.

## Development environment

- **great_tables** Version: 0.4.0

**Comment by jrycw** [comment]
It appears that the issue originates from the following line:
https://github.com/posit-dev/great-tables/blob/b4d102a3576583fe561fbf9728457c5dde0b6493/great_tables/_utils_render_html.py#L179-L181

Setting `ids` to `False` seems to resolve the issue. However, this change may have implications on subsequent logic, requiring further investigation by the team.
