### ISSUE TITLE
Add ability to format as accounting values (in `fmt_*()` methods where it makes sense)

### ISSUE THREAD

**Issue by rich-iannone** [posit-dev/great-tables#278]
We currently don't have the ability to format numeric values as accounting-type values (i.e., handling of negative values different than using the minus sign). This should ideally work inside:

- `fmt_number()`
- `fmt_integer()`
- `fmt_currency()`
- `fmt_percent()`

As for how it would look, this is a good start:

<img width="625" alt="accounting_values" src="https://github.com/posit-dev/great-tables/assets/5612024/28cfe1a1-0ed3-448c-b35e-9538ca1ef55d">

**Comment by JulianCologne** [comment]
Great Idea! 😃 

Not sure if this is just to show the format but the "percent" **value** looks wrong 😄 .
Most programms (like excel, powerbi, ...) multiply by 100 and not divide by 10 😮 .

For example you perform a calculation resulting in `0.15` and formatted as percent yields `15%` (`1 = 100%`)

**Comment by rich-iannone** [comment]
I rescaled the number before applying the percent formatting (to put it in a better range).
