### ISSUE TITLE
Table output cannot be suppressed in Quarto when R code chunk present

### ISSUE THREAD

**Issue by AlbertRapp** [posit-dev/great-tables#291]
## Prework

- [x] Read and agree to the [code of conduct](https://www.contributor-covenant.org/version/2/1/code_of_conduct/) and [contributing guidelines](https://github.com/posit-dev/great_tables/blob/main/.github/CONTRIBUTING.md).
- [x] If there is [already a relevant issue](https://github.com/posit-dev/great_tables/issues), whether open or closed, comment on the existing thread instead of posting a new issue.

## Description

Hi there :wave: 

This is probably not a highly relevant edge case. But in Quarto the option `output: false` doesn't work with `gt` tables if there are both R and Python code chunks in the Quarto file. For other Python outputs, output suppression seems to be unaffected.

## Reproducible example

- [x] Post a minimal reproducible example (MRE) so the maintainer can troubleshoot the problems you identify. A reproducible example is:
  - [x] **Runnable**: post enough code and data so any onlooker can create the error on their own computer.
  - [x] **Minimal**: reduce runtime wherever possible and remove complicated details that are irrelevant to the issue at hand.
  - [x] **Readable**: format your code according to the [Style Guide for Python Code](https://peps.python.org/pep-0008/).

````qmd

```{r}
#| output: false
# R code chunk
1 + 1
```

```{python}
#| output: false
# This PYTHON output is suppressed
1 + 1
```

```{python}
#| output: false
import great_tables as gt

# This PYTHON output is ONLY suppressed if 
# the above R code chunk is not there
gt.GT(gt.data.gtcars)
```

````

## Expected result

No table in the output

## Development environment

- Operating System: Ubuntu
- great-tables==0.5.0

**Comment by machow** [comment]
I've opened an issue on quarto--thanks for such a helpful qmd reproducing the issue!

**Comment by machow** [comment]
Just to complete the loop -- I don't think there's currently a simple option for suppressing objects with a `_repr_html_()` method, for the case where quarto punts to knitr (which is what it does when there are R and python code chunks).

However, one quick solution is to put a semi colon to suppress the output altogether:

``````
```{python}

class MyClass:
    def _repr_html_(self):
        return "<p>uh-oh</p>"


MyClass();               # <---- NOTE THE SEMI COLON 
```
``````
