### ISSUE TITLE
Remove unnecessary top-level imports

### ISSUE THREAD

**Issue by machow** [posit-dev/great-tables#293]
Based on convo w/ @rich-iannone, it seems like there may be some unused helper functions exposed at the top-level (e.g. letters, LETTERS, px). Let's go through the top-level imports and decide which need to stay, and which might be removed.

related to https://github.com/posit-dev/great-tables/pull/289#pullrequestreview-2004309576

**Comment by jrycw** [comment]
Perhaps it's a good time to incorporate this cleanup with [#119 isort](https://github.com/posit-dev/great-tables/issues/119)?

**Comment by rich-iannone** [comment]
We'll come to this later and then fully integrate isort into our dev practices.
