### ISSUE TITLE
Add examples to any Reference pages that don't have any

### ISSUE THREAD

**Issue by machow** [posit-dev/great-tables#322]
Currently, a few reference pages don't have examples. Let's be sure to fill in examples for some of the pages that don't have them. (It seems like most do).

**Comment by jrycw** [comment]
@machow and @rich-iannone , would it be alright if I tackle this issue after #315 is merged? I could take the opportunity to review all the documentation for code, check for typos and type hints, formatting issues, and add examples if anything is missing.

**Comment by rich-iannone** [comment]
Sorry for the delay in responding, but that would be great @jrycw !
