### ISSUE TITLE
Nanoplots compact formatting gets applied before removing exponent, causing error

### ISSUE THREAD

**Issue by machow** [posit-dev/great-tables#334]
```python
import polars as pl
from great_tables import GT

df = pl.DataFrame({"x": [[1, 2], [7045, 3]]})
GT(df).fmt_nanoplot("x", plot_type="bar")
```

raises this error:

<img width="824" alt="image" src="https://github.com/posit-dev/great-tables/assets/2574498/71a50c94-4eb7-4e31-8bcf-144501a44e0d">

This is because 7045 is converted to `'7.04K'`, and then `_remove_exponent()` is trying to convert that to a decimal.

**Comment by rich-iannone** [comment]
Fixed by https://github.com/posit-dev/great-tables/pull/335.
