### ISSUE TITLE
How to style stub?

### ISSUE THREAD

**Issue by dafriedman97** [posit-dev/great-tables#385]
Is it possible to add styling in the stub? I can style a regular column like this:
```
from great_tables import GT, md, html, style, loc
from great_tables.data import islands

islands_mini = islands.head(5)
(
    GT(islands_mini)
    .tab_stub(rowname_col="name")
    .tab_style(
        style=style.fill('lightgray'),
        locations=loc.body(columns=['size'])
    )
)
```
<img width="146" alt="image" src="https://github.com/posit-dev/great-tables/assets/41458150/79adcbf7-3d89-4529-aebf-1f9cce16b42e">

But how could I style the stub group (i.e. make the geographical names colored)?

**Comment by jrycw** [comment]
@dafriedman97, maybe try using `tab_options`:
```python
from great_tables import GT, loc, style
from great_tables.data import islands

islands_mini = islands.head(5)
(
    GT(islands_mini)
    .tab_stub(rowname_col="name")
    .tab_style(style=style.fill("lightgray"), locations=loc.body(columns=["size"]))
    .tab_options(stub_background_color="lightgreen")
)
```
![image](https://github.com/posit-dev/great-tables/assets/67060418/a2f065b9-20ec-4d40-a4ae-c907040d3fea)
