### ISSUE TITLE
Verify that `html()` and `md()` work everywhere

### ISSUE THREAD

**Issue by machow** [posit-dev/great-tables#39]
Let's double check everywhere that html and md could go is rendered correctly (and add tests).

We tested one case by snapshot testing `create_body_component_h`. That could be a good way to test the other places html() and md() could be used.

**Comment by rich-iannone** [comment]
Discovered that `md()`/`html()` doesn't currently work with `tab_source_note()`.

**Comment by rich-iannone** [comment]
This'll be fixed with https://github.com/posit-dev/great-tables/pull/77.
