### ISSUE TITLE
Wrap header rows in `<thead>`

### ISSUE THREAD

**Issue by cwickham** [posit-dev/great-tables#403]
## Prework

- [X] Read and agree to the [code of conduct](https://www.contributor-covenant.org/version/2/1/code_of_conduct/) and [contributing guidelines](https://github.com/posit-dev/great_tables/blob/main/.github/CONTRIBUTING.md).
- [X] If there is [already a relevant issue](https://github.com/posit-dev/great_tables/issues), whether open or closed, comment on the existing thread instead of posting a new issue.

## Description

Header rows should always be wrapped in `<thead>`. In particular, this will mean tables output to Typst that break over pages get the header rows repeated on each page.

## Reproducible example

Consider the following example:
```python
from great_tables import GT, md, html
from great_tables.data import islands

gt_tbl = GT(islands)
# Show the output table
gt_tbl
```

This results in the following (partial) HTML:

```html
<table class="gt_table" data-quarto-disable-processing="false" data-quarto-bootstrap="false">

<tr class="gt_col_headings">
  <th class="gt_col_heading gt_columns_bottom_border gt_left" rowspan="1" colspan="1" scope="col" id="name">name</th>
  <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1" scope="col" id="size">size</th>
</tr>
<tbody class="gt_table_body">
...
```

If this table is used in Quarto with `format: typst` and is allowed to break over pages, the header rows are not repeated on the second page:

<img width="634" alt="Screenshot 2024-07-18 at 11 01 42 AM" src="https://github.com/user-attachments/assets/b8a04639-6c69-4473-951e-fad950036b30">

<details>
  <summary>QMD</summary>

````markdown
---
title: "Untitled"
format: typst
keep-md: true
---

```{=typst}
#show figure: set block(breakable: true)
```
```{python}
from great_tables import GT, md, html
from great_tables.data import islands

gt_tbl = GT(islands)
# Show the output table
gt_tbl
```
````
</details>

## Expected result

E.g. in `gt` the header rows are nested inside `<thead>`, 
```{html}
<table class="gt_table" data-quarto-disable-processing="false" data-quarto-bootstrap="false">
  <thead>
    <tr class="gt_col_headings">
      <th class="gt_col_heading gt_columns_bottom_border gt_left" rowspan="1" colspan="1" scope="col" id="name">name</th>
      <th class="gt_col_heading gt_columns_bottom_border gt_right" rowspan="1" colspan="1" scope="col" id="size">size</th>
    </tr>
  </thead>
  <tbody class="gt_table_body">
```

Then the header rows are repeated on the second page:

<img width="630" alt="Screenshot 2024-07-18 at 11 05 32 AM" src="https://github.com/user-attachments/assets/5999f1ef-6002-4493-b026-60d9f1a2c624">

## Development environment

- Operating System: macOS Sonoma 14.4
- **great_tables** Version: 0.10.0
- Quarto: dev version

**Comment by machow** [comment]
@cwickham we are adding thead in #421 -- does this look okay for the typst work?

[Here's a snapshot](https://github.com/posit-dev/great-tables/pull/421/files#diff-6c8278604b88d9612f914231f8cb9bd599f09b9f75931802374c201f94c11843) showing the new thead placement (note that thead now closes on line 66 in the new code in the diff)

**Comment by cwickham** [comment]
Yeah, that looks great!
