### ISSUE TITLE
Jupyter Notebook

### ISSUE THREAD

**Issue by WndrWild** [posit-dev/great-tables#411]
## Prework

- [x] Read and agree to the [code of conduct](https://www.contributor-covenant.org/version/2/1/code_of_conduct/) and [contributing guidelines](https://github.com/posit-dev/great_tables/blob/main/.github/CONTRIBUTING.md).
- [x] If there is [already a relevant issue](https://github.com/posit-dev/great_tables/issues), whether open or closed, comment on the existing thread instead of posting a new issue.

## Question

Does great_tables work within jupyter notebooks?

**Comment by david-waterworth** [comment]
It works fine for me with vscode notebooks (which are based of jupyter)

**Comment by WndrWild** [comment]
I just tried in Google Co-lab and it runs fine. There must be some issue with my local installation of Jupyter Notebook.

**Comment by jrycw** [comment]
Since no further discussion has taken place, I will close this issue.
