### ISSUE TITLE
Allow images to be used as column headers

### ISSUE THREAD

**Issue by minimav** [posit-dev/great-tables#418]
## Prework

- [x] Read and abide by the **great_tables** [code of conduct](https://www.contributor-covenant.org/version/2/1/code_of_conduct/) and [contributing guidelines](https://github.com/posit-dev/great_tables/blob/main/.github/CONTRIBUTING.md).
- [x] Search for duplicates among the [existing issues](https://github.com/posit-dev/great_tables/issues) (both open and closed).

## Proposal

This can be achieved in a couple of ways already, although they both are very hacky. One is by using placeholder column names and replacing them appropriately in the HTML output created by `as_raw_html` with base64 encoded `<img>` tags (essentially the approach that is used in `fmt_image`).

A couple of approaches that might work for a proper implementation this:

* A `.fmt_column_header_image` method that mimicks `fmt_image` and reuses `FmtImage` if possible.

```python
df = pl.DataFrame([
    {"column_name": 1.0}
])

GT(df).fmt_column_header_image(
     column_name=<path to image>,
     # fmt_image kwargs
     height=...
)
```

* Allow option in `.col_labels` to enable use of an image instead of a renaming label, or infer from argument type

```python
df = pl.DataFrame([
    {"regular_name": 1.0, "image_column": "something"}
])

GT(df).col_labels(
    regular_name="some other name",
    # infer from Path type?
    image_column=Path(...),
)
```

I would be happy to try implementing something like this. Thank you 😄

**Comment by jrycw** [comment]
Thank you for bringing this issue to our attention. I'll close it now, as the [vals.fmt_image()](https://posit-dev.github.io/great-tables/reference/vals.fmt_image.html#great_tables.vals.fmt_image) function is available to achieve the desired result.
