### ISSUE TITLE
gt.opt_row_striping unexpected keyword argument row_striping_include_table_body

### ISSUE THREAD

**Issue by aronatkins** [posit-dev/great-tables#435]
## Prework

- [x] Read and agree to the [code of conduct](https://www.contributor-covenant.org/version/2/1/code_of_conduct/) and [contributing guidelines](https://github.com/posit-dev/great_tables/blob/main/.github/CONTRIBUTING.md).
- [x] If there is [already a relevant issue](https://github.com/posit-dev/great_tables/issues), whether open or closed, comment on the existing thread instead of posting a new issue.

## Description

Attempting to disable row striping presents an error.

## Reproducible example

```python
from great_tables import GT
import polars

data = polars.DataFrame({
    "first": ["alice", "bob"],
    "last": ["smith", "smith"],
})
table = GT(data)
table.opt_row_striping(False)
```

```
Traceback (most recent call last):
  File "PROJECT_DIR/bug.py", line 9, in <module>
    table.opt_row_striping(False)
  File "PROJECT_DIR/env/lib/python3.11/site-packages/great_tables/_options.py", line 619, in opt_row_striping
    return tab_options(self, row_striping_include_table_body=row_striping)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: tab_options() got an unexpected keyword argument 'row_striping_include_table_body'
```

## Expected result

What should have happened? Please be as specific as possible.

Row striping is disabled without error.

## Development environment

- Operating System: macOS
- **great_tables** Version: 0.11.0

## Additional context

Directly calling `gt.tab_options(row_striping_include_table_body=False)` presented the same error.

**Comment by jrycw** [comment]
It seems that this option is not officially released (it is hidden from `GT.tab_options()`).

**Comment by aronatkins** [comment]
@jrycw - The option is present in the published documentation, which is how I found it.
https://posit-dev.github.io/great-tables/reference/GT.html#great_tables.GT.opt_row_striping

**Comment by aronatkins** [comment]
It's not important for this issue, but I was trying to build tables in both R and Python. The R package also has a public function: https://gt.rstudio.com/reference/opt_row_striping.html

**Comment by rich-iannone** [comment]
Sorry you bumped into this problem. I will work on getting row striping generally working in Great Tables for the upcoming release.

**Comment by rich-iannone** [comment]
Row striping (with `opt_row_striping()` and three args in `tab_options()`) has now been implemented in the recently-merged https://github.com/posit-dev/great-tables/pull/461. It'll be available in the next release so closing this issue as done!
