### ISSUE TITLE
Encoding issue on windows when saving a table

### ISSUE THREAD

**Issue by bart-r-willems** [posit-dev/great-tables#440]
## Description

When saving a table with the `save` message, an exception occurs in Windows.

## Reproducible example

- Run pandas/jupyter on a windows maching
- create a simple table
- try saving e.g. `df.pipe(GT).save('test.pdf')`

**The bottom of the stack trace shows this**

    File D:\Python\Python312\Lib\site-packages\great_tables\_export.py:310, in save(self, file, selector, scale, expand, web_driver, window_size, debug_port, _debug_dump)
        303 with (
        304     tempfile.TemporaryDirectory() as tmp_dir,
        305     wdriver(options=wd_options) as headless_browser,
        306 ):
        307 
        308     # Write the HTML content to the temp file
        309     with open(f"{tmp_dir}/table.html", "w") as temp_file:
    --> 310         temp_file.write(html_content)
        312     # Open the HTML file in the headless browser
        313     headless_browser.set_window_size(window_size[0], window_size[1])

    File D:\Python\Python312\Lib\encodings\cp1252.py:19, in IncrementalEncoder.encode(self, input, final)
         18 def encode(self, input, final=False):
    ---> 19     return codecs.charmap_encode(input,self.errors,encoding_table)[0]

    UnicodeEncodeError: 'charmap' codec can't encode character '\u2212' in position 7916: character maps to <undefined>

Note that the error occurs due to CP1252 encoding which is the default. I fixed it by adding `encoding='utf-8'` ib line 309 of the _export.py file:

        # Write the HTML content to the temp file
        with open(f"{tmp_dir}/table.html", "w", encoding='utf-8') as temp_file:
            temp_file.write(html_content)

(Sorry I'm not comfortable with pull requests I don't want to ruin anything)

## Expected result

A file `test.pdf` should be created

## Development environment

- Operating System:  Windows 10, Python 3.12.4
- **great_tables** Version: 0.11.0

**Comment by HansMellman** [comment]
Encountering the same issue when trying to utilize a Unicode character in the heading section (in lieu of an image). Unable to figure out a workaround yet without just removing the character.

**Comment by bart-r-willems** [comment]
I just tested it, with my fix in place that works without issues (windows
10, python 3.12.4)

**Comment by HansMellman** [comment]
You sir, are wonderful. Thank you for that - did the trick perfectly! Hopefully they'll be able to implement the fix natively.

**Comment by jrycw** [comment]
I'll close this issue as the Unicode problem has been resolved. [GT.save()](https://posit-dev.github.io/great-tables/reference/GT.save.html#great_tables.GT.save) now includes an `encoding` parameter, which defaults to `utf-8` and allows users to specify other encodings if needed.
