### ISSUE TITLE
docs: rendering issue for `GT.fmt_*()` functions

### ISSUE THREAD

**Issue by jrycw** [posit-dev/great-tables#476]
It seems we’re encountering a documentation rendering issue with `GT.fmt_*()` functions. For example, see the issue with [GT.fmt_integer()](https://posit-dev.github.io/great-tables/reference/GT.fmt_integer.html#adapting-output-to-a-specific-locale-.doc-section-.doc-section-adapting-output-to-a-specific-locale).

![image](https://github.com/user-attachments/assets/88eca858-ddd6-4486-9ace-6d4beeaeec6c)

**Comment by rich-iannone** [comment]
@machow I can reproduce this in a local docs site build using Quarto `1.5.57` (latest prerelease, same as in CI) *and* after updating `quartodoc` with

```
pip install git+https://github.com/machow/quartodoc.git@a98bf47004a76578e6893b4ba6d9447322137a3c
```

as was recently done for CI (in https://github.com/posit-dev/great-tables/commit/871ca1ca749a1e6c0d97f20907f8be73b07d136c).

*Before* updating `quartodoc` on my system, the local build of the docs showed a correctly rendered heading on the `great-tables/docs/_site/reference/GT.fmt_integer.html` page.

**Comment by rich-iannone** [comment]
FWIW I built the site locally again with Quarto `1.6.18` (latest prerelease) with the `a98bf`-commit build of `quartodoc` and the issue persists.

**Comment by machow** [comment]
Shoot, we're now using the latest quartodoc commit, which tries to add html class attributes to titles. However, I think something about this custom section header in the docstring is messing with that :/. The classes are correctly being added to sections like "Examples".

I'm building the docs locally and will take a look!

**Comment by machow** [comment]
shoot, quartodoc does not expect titles to have special characters (like the backtick) in them, so the markdown to add classes to the title has backticks included in it :/

```
## Returns {.doc-section .doc-section-returns}

...

## Adapting Output To A Specific `Locale` {.doc-section .doc-section-Adapting-output-to-a-specific-`locale`}

NOTE THE `locale` above ----^
...

## Examples {.doc-section .doc-section-examples}

```

**Comment by jrycw** [comment]
Thanks to @machow for the quick fix! I’ll go ahead and close the issue.

**Comment by jrycw** [comment]
@machow , I’m not sure if this is related to the recent fix, but it looks like some descriptions in the docs are now showing rendering issues with backslashes appearing before double quotes (`"`). For example:

![Image](https://github.com/user-attachments/assets/b497d205-9a72-4f1f-93e5-64aa21032ee4)

I'll reopen the issue—please feel free to close it if it's not relevant.

**Comment by machow** [comment]
Shoot, thanks for surfacing 😓

**Comment by jrycw** [comment]
The new style of the site looks REALLY great, and since the escaping issue has been resolved, I'll proceed to close the issue.
