### ISSUE TITLE
GT.save does not work with pathlib Path

### ISSUE THREAD

**Issue by lwanger** [posit-dev/great-tables#479]
## Prework

- [X ] Read and agree to the [code of conduct](https://www.contributor-covenant.org/version/2/1/code_of_conduct/) and [contributing guidelines](https://github.com/posit-dev/great_tables/blob/main/.github/CONTRIBUTING.md).
- [ X] If there is [already a relevant issue](https://github.com/posit-dev/great_tables/issues), whether open or closed, comment on the existing thread instead of posting a new issue.

## Description

Saving tables using GT.save does not work when a pathlib Path is used for the file parameter. Unfortunately, running this example gives the following Exception:

## Reproducible example

from pathlib import Path
import pandas as pd

data = {'A': [1,2,3], 'B': ['foo', 'bar', 'baz'], }
df = pd.DataFrame(data)
tbl = (gt.GT(df))

out_file = Path("table_export.pdf")
tbl.save(file=out_file)

- [X] Post a minimal reproducible example (MRE) so the maintainer can troubleshoot the problems you identify. A reproducible example is:
  - [X] **Runnable**: post enough code and data so any onlooker can create the error on their own computer.
  - [X] **Minimal**: reduce runtime wherever possible and remove complicated details that are irrelevant to the issue at hand.
  - [X] **Readable**: format your code according to the [Style Guide for Python Code](https://peps.python.org/pep-0008/).

## Expected result

This should save the file without an error.

## Development environment

- Operating System: [e.g., Linux, macOS, Windows]
- **great_tables** Version: [e.g., 0.0.1]

**Comment by lwanger** [comment]
Sorry, this issue posted before I was done editing. A few more details:

- GT version: 0.1
- OS: Windows 11
- Python version: 3.11

As a work-around can convert the Path to a string, e.g.:

tbl.save(file=str(Path("table_export.pdf")))

**Comment by machow** [comment]
Should be resolved in v0.13.0 (releasing now!)

**Comment by lwanger** [comment]
Thank you! Next time I'll do a pull request.

Len
________________________________
