### ISSUE TITLE
`cols_width()` not stretching the cell values

### ISSUE THREAD

**Issue by mthomas-ketchbrook** [posit-dev/great-tables#491]
## Prework

- [x] Read and agree to the [code of conduct](https://www.contributor-covenant.org/version/2/1/code_of_conduct/) and [contributing guidelines](https://github.com/posit-dev/great_tables/blob/main/.github/CONTRIBUTING.md).
- [x] If there is [already a relevant issue](https://github.com/posit-dev/great_tables/issues), whether open or closed, comment on the existing thread instead of posting a new issue.

## Description

The `cols_width()` function does not appear to be stretching the cell text to the full width of the column.

## Reproducible example

- [x] Post a minimal reproducible example (MRE) so the maintainer can troubleshoot the problems you identify. A reproducible example is:
  - [x] **Runnable**: post enough code and data so any onlooker can create the error on their own computer.
  - [x] **Minimal**: reduce runtime wherever possible and remove complicated details that are irrelevant to the issue at hand.
  - [x] **Readable**: format your code according to the [Style Guide for Python Code](https://peps.python.org/pep-0008/).

```
from great_tables import GT, style, exibble

exibble_mini = exibble[["num", "char", "date", "datetime", "row"]].head(5)

exibble_mini['long_text'] = 'Here is a really long sentence that I want to ensure is being handled appropriately by the cols_width argument, but I cannot get it to work unfortunately. I appreciate you taking the time to read this issue.'

(
    GT(exibble_mini)
    .cols_hide(columns = 'datetime')
    .cols_width(
        cases={
            "num": "50px",
            "char": "50px",
            "date": "50px",
            "row": "50px",
            "long_text": "400px"
        }
    )
)
```

This returns a GT that looks like this:

![Image](https://github.com/user-attachments/assets/38fa8db6-cc86-4583-91d3-cd6dc3d47a47)

## Expected result

I would have expected the text in the cells in the `long_text` column to have stretched horizontally and wrap every 400px.  I would have expected the final output to look something more like this:

![Image](https://github.com/user-attachments/assets/bdcc2d52-e216-4b29-b173-2c722ecf7d59)

## Development environment

- Operating System: Linux 
- **great_tables** Version: 0.13.0

I've also created this repository with a VSCode Dev Container environment for reproducibility: https://github.com/mthomas-ketchbrook/great-tables-cols-width-bug.  The [example.qmd](https://github.com/mthomas-ketchbrook/great-tables-cols-width-bug/blob/main/example.qmd) file contains the reproducible example I referenced above.

## Additional context

This seems like it may be particular to setting the width of the *last* column in the GT table.

**Comment by machow** [comment]
Hey, thanks for raising this and including example code. It appears that an extra `<col />` element is inside the `<colgroup>` tag, which sets the widths. Let us dig a bit deeper into a fix!

**Comment by mthomas-ketchbrook** [comment]
Thank you, @machow !
