### ISSUE TITLE
[pyOpenSci review] make `Text` a subclass of `str` instead of a single attribute dataclass

### ISSUE THREAD

**Issue by rich-iannone** [posit-dev/great-tables#536]
From the pyOpenSci comment:

suggestion (_text.py): Maybe we could make Text a subclass of str instead of a single attribute dataclass. We would get rid of quite a few types checks errors.

https://github.com/pyOpenSci/software-submission/issues/202#issuecomment-2480804958

**Comment by machow** [comment]
We have changed this to now use an interface called BaseText, with only `.to_html()` and `.to_latex()` methods.

The interface now only requires these methods, and does not specify what data / attributes the class should hold. I think this gets back at what the reviewer noted -- with the twist that now our interface now doesn't have opinions on how an object is instantiated.
