### ISSUE TITLE
[pyOpenSci review] Consider consolidating files with only one function into others

### ISSUE THREAD

**Issue by rich-iannone** [posit-dev/great-tables#539]
From the pyOpenSci comment:

issue (general): There are a fair number of files with just one pass-through function. Is this because you want to keep the codebase as close as possible to gt's, or is it just a refactoring waiting to be done?

https://github.com/pyOpenSci/software-submission/issues/202#issuecomment-2480804958

**Comment by rich-iannone** [comment]
Here's an accounting of some small .py files, categorized by what's in them.

Files with a single (unexported) function:

- `_body.py`: `body_reassemble()`
- `_stub.py`: `reorder_stub_df()`
- `_quarto.py`: `is_quarto_render()`

Files with a single exported function:

- `_heading.py`: `tab_header()`
- `_pipe.py`: `pipe()`
- `_source_notes.py`: `tab_source_note()`
- `_stubhead.py`: `tab_stubhead()`
- `utils_render_common.py`: `get_row_reorder_df()`

Short files with types:

- `_types.py`
- `loc.py`
- `style.py`
- `vals.py`

'Empty' files

- `_footnotes.py`
- `_row_groups.py`

**Comment by machow** [comment]
I think that modules like `_quarto.py` are there to signal a very explicit layer to an external tool.  It looks like some of the others could be refactored (e.g. `body_reassemble()` is a passthrough function). I'm going to close, but we'll need get around to cleaning some of this up 😓
