### ISSUE TITLE
[pyOpenSci review] remove imports from function scope wherever possible

### ISSUE THREAD

**Issue by rich-iannone** [posit-dev/great-tables#540]
From the pyOpenSci comment:

issue (_boxhead.py, _formats.py, _modify_rows.py, _spanners.py, _utils_nanoplots.py, others): I can spot a few places where we could move some import statements to the top of the file instead of being in functions. AFAICT there is no circular import issue there, and it does not seem to be for performance reasons either.

https://github.com/pyOpenSci/software-submission/issues/202#issuecomment-2480804958

**Comment by rich-iannone** [comment]
List of functions that contain imports:

- [ ] `cols_label()`: `from great_tables._helpers import UnitStr`
- [ ] `save()`: `import base64`
- [ ] `save()`: `from ._utils_selenium import _get_web_driver`
- [ ] `_save_screenshot()`: `from io import BytesIO`
- [ ] `_save_screenshot()`: `from selenium.webdriver.common.by import By`
- [ ] `_save_screenshot()`: `from selenium.webdriver.support import expected_conditions as EC`
- [ ] `_save_screenshot()`: `from selenium.webdriver.support.ui import WebDriverWait`
- [ ] `_save_screenshot()`: `from PIL import Image`
- [ ] `fmt_units()`:  `from great_tables._helpers import define_units`
- [ ] `FmtImage`/`to_latex()`: `from warnings import warn`
- [ ] `FmtImage`/`to_latex()`:  `from ._gt_data import FormatterSkipElement`
- [ ] `FmtIcon`/`to_latex()`: `from warnings import warn`
- [ ] `FmtIcon`/`to_latex()`:  `from ._gt_data import FormatterSkipElement`
- [ ] `FmtFlag`/`to_latex()`: `from warnings import warn`
- [ ] `FmtFlag`/`to_latex()`:  `from ._gt_data import FormatterSkipElement`
- [ ] `fmt_nanoplot(): `from great_tables._utils import _str_detect`

**Comment by machow** [comment]
We plan to circle back to this, and have noted it, but I'm going to close here for now.
