### ISSUE TITLE
[pyOpenSci review] Better integrate notebook-based examples

### ISSUE THREAD

**Issue by rich-iannone** [posit-dev/great-tables#545]
From the pyOpenSci comment:

Some of the examples are linking to the GitHub repository with pre-rendered notebooks. I don't like it so much and I usually prefer a solution like sphinx-gallery allowing a nicer integration with the documentation and provide examples that can be downloaded.

https://github.com/pyOpenSci/software-submission/issues/202#issuecomment-2489584108

**Comment by machow** [comment]
I think this feedback makes a lot of sense -- pre-rendered notebooks in github aren't an ideal way to view examples. Our hope with making 1 of our 8 examples link to a notebook in github, was to show examples in a variety of outputs. I think we wouldn't want to do much more linking to github notebooks.
