### ISSUE TITLE
Displaying the result of great table produces errors

### ISSUE THREAD

**Issue by lwilhoit** [posit-dev/great-tables#561]
I tried to run the example code:

from great_tables import GT, md, html
from great_tables.data import islands

islands_mini = islands.head(10)

gt_tbl = GT(islands_mini)

# Show the output table
print(gt_tbl)

The result was:

GT(_tbl_data=           name   size
0        Africa  11506
1    Antarctica   5500
2          Asia  16988
3     Australia   2968
4  Axel Heiberg     16
5        Baffin    184
6         Banks     23
7        Borneo    280
8       Britain     84
9       Celebes     73, _body=<great_tables._gt_data.Body object at 0x000001A97FE59100>, _boxhead=Boxhead([ColInfo(var='name',

I expected to get the formatted table.

- Operating System: Windows 11
- Python 3.12.7
- **great_tables** Version: 0.14.0

**Comment by jrycw** [comment]
@lwilhoit , I’d recommend checking out a similar issue discussed in #406.

**Comment by lwilhoit** [comment]
Thank you!  That solved the problem.

**Comment by jrycw** [comment]
Glad to hear it was helpful! I’ll go ahead and close the issue.
