### ISSUE TITLE
Adding any code after the great-tables code in Quarto fails to render the great-tables table

### ISSUE THREAD

**Issue by karangattu** [posit-dev/great-tables#64]
## Description

Adding any code after the great-tables code in Quarto fails to render the great-tables table

## Reproducible example

use the following code:
```python
from great_tables import GT
from great_tables.data import countrypops

import polars as pl
import polars.selectors as cs

# Get vectors of 2-letter country codes for each region of Oceania
countries = {
    "Australasia": ["AU", "NZ"],
    "Melanesia": ["NC", "PG", "SB", "VU"],
    "Micronesia": ["FM", "GU", "KI", "MH", "MP", "NR", "PW"],
    "Polynesia": ["PF", "WS", "TO", "TV"],
}

# a dictionary mapping region to country (e.g. AU -> Australasia)
region_to_country = {
    region: country for country, regions in countries.items() for region in regions
}

keep_rows = countrypops.country_code_2.isin(list(region_to_country)) & countrypops.year.isin(
    [2000, 2010, 2020]
)

# Create a gt table based on a preprocessed `countrypops`
wide_pops = (
    pl.from_pandas(countrypops)
    .filter(
        pl.col("country_code_2").is_in(list(region_to_country))
        & pl.col("year").is_in([2000, 2010, 2020])
    )
    .with_columns(pl.col("country_code_2").replace(region_to_country).alias("region"))
    .pivot(index=["country_name", "region"], columns="year", values="population")
    .sort("2020", descending=True)
)

(
    GT(wide_pops, rowname_col="country_name", groupname_col="region")
    .tab_header(title="Populations of Oceania's Countries in 2000, 2010, and 2020")
    .tab_spanner(label="Total Population", columns=cs.all())
    .fmt_integer()
)
print("extra lines")
```
## Demo

![gt print issue](https://github.com/posit-dev/great-tables/assets/4220325/c99dc507-a262-4d00-b0c9-9dab4e561312)

## Expected result

Should show the table followed by the print statement
## Development environment

- Operating System: macOS,
- **great_tables** Version: 0.1.1

**Comment by machow** [comment]
Thanks for surfacing! I think this is the intended behavior in quarto. Like jupyter notebooks, only the last expression's output gets printed (unless it's inside a print or IPython.display.display call).

I'm not sure where exactly in the quarto docs this is mentioned though :/. Basically qmd files get converted to ipynb, and then run, so this behavior from jupyter occurs.

(Maybe somewhere around here they should mention it?: https://quarto.org/docs/tools/jupyter-lab.html)

**Comment by machow** [comment]
For posterity, I just remembered there's a sort of kludgy way to have it represent the output of all expressions (similar to executing R in quarto):

```python
shell = get_ipython()

# by default this is set to "last_expr"
shell..ast_node_interactivity = "all"
```
