### ISSUE TITLE
Example on website has commented code

### ISSUE THREAD

**Issue by karangattu** [posit-dev/great-tables#65]
## Description

Example on website has commented code

## Reproducible example

Navigate to [examples page](https://posit-dev.github.io/great-tables/examples/). Observe the code for `Populations of Oceania's Countries`

![gt example has commented code](https://github.com/posit-dev/great-tables/assets/4220325/e41def07-2a58-4069-87f4-a576d10d1bef)

## Expected result

If commented code is not relevant to the example, it should be removed.

**Comment by rich-iannone** [comment]
Thanks Karan. This is now fixed with https://github.com/posit-dev/great-tables/commit/dd4f31534fdce7657be42508236348f68ee96861.
