### ISSUE TITLE
epic: make pandas an optional dependency

### ISSUE THREAD

**Issue by machow** [posit-dev/great-tables#7]
**Edit:** polars support is complete! This issue now tracks only the removing of pandas as a mandatory dependency. This is largely a code cleanup activity, since the machinery to make pandas optional is already in great tables.

~This may take a bit of work, but using the approach in https://github.com/machow/databackend, we should be able to make pandas and polars optional dependencies.~

~There is a data decorator pattern used in `_tbl_data.py` that wraps a dataframe to provide standard methods (e.g. for getting column names). We should be able to use generic functions, so gt can call things like `get_column_names` directly on any DataFrame.~

**Comment by johnros** [comment]
In the meanwhile, worth updating the DT() documentation clarifying that `dataframe` refers to `pd.Dataframe()`.

**Comment by machow** [comment]
Polars is supported (though pandas is still an optional dependency)! I'll update this issue to reflect that the remaining thing is making pandas optional.
