### ISSUE TITLE
tab_source_note disappears when text is rendered as markdown

### ISSUE THREAD

**Issue by karangattu** [posit-dev/great-tables#73]
## Description

`tab_source_note` disappears when text is rendered as markdown

## Reproducible example
using
```python
    .tab_source_note(
        source_note = "Source: The World Almanac and Book of Facts, 1975, page 406."
    )
```
renders the text correctly
<img width="458" alt="great_tables_-_Examples" src="https://github.com/posit-dev/great-tables/assets/4220325/8963e44a-66c1-4d77-b38c-1a8fe05ee6e5">
but adding
```python
    .tab_source_note(
        source_note = md("Reference: McNeil, D. R. (1977) *Interactive Data Analysis*. Wiley.")
    )
```
Does not render the markdown and hides the text from the footnotes section

## source code
```python
from great_tables import GT, md, html
from great_tables.data import islands

islands_mini = islands.head(10)

(
    GT(islands_mini, rowname_col = "name")
    .tab_header(
        title = "Large Landmasses of the World",
        subtitle = "The top ten largest are presented"
    )
    .tab_source_note(
        source_note = "Source: The World Almanac and Book of Facts, 1975, page 406."
    )
    .tab_source_note(
        source_note = md("Reference: McNeil, D. R. (1977) *Interactive Data Analysis*. Wiley.")
    )
    . tab_stubhead(label = "landmass")
)
```

## Expected result

Should render footnote with markdown when used in conjunction with the `md` tag
## Development environment

- Operating System: macOS
- **great_tables** Version: 0.1.1

## Additional context

This code is also displayed on the examples page

**Comment by rich-iannone** [comment]
Thanks for reporting. Will fix this soon!
