### ISSUE TITLE
Option to export tables to LaTeX code

### ISSUE THREAD

**Issue by aeturrell** [posit-dev/great-tables#75]
## Prework

- [x] Read and abide by the **great_tables** [code of conduct](https://www.contributor-covenant.org/version/2/1/code_of_conduct/) and [contributing guidelines](https://github.com/posit-dev/great_tables/blob/main/.github/CONTRIBUTING.md).
- [x] Search for duplicates among the [existing issues](https://github.com/posit-dev/great_tables/issues) (both open and closed).

## Proposal

It would be fantastic if there was an option to export tables to LaTeX as this would unlock a wide range of further uses in presentations, papers, and reports. For prior art, the original **gt** package in R does this, and **pandas** has a table export option.

Thanks for the great work on great tables!

**Comment by rich-iannone** [comment]
Yes! We are planning for this, and it'll be something that's done in early-to-mid 2024. The reason for it being scheduled a bit later is so we could first get the core functionality into this package working well.

**Comment by aeturrell** [comment]
Amazing news, thank you.

**Comment by apoorvkh** [comment]
Just wondering, do you think this will be implemented by the next version? Or a longer timeline?

Would love to ditch my [`pandas` dependency](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.to_latex.html) and rely on `polars` and `great-tables` instead!

**Comment by machow** [comment]
We should have the more fine-grained styling options implemented pretty soon (https://github.com/posit-dev/great-tables/pull/341), which will be useful to have in place before implementing latex support. Lemme check with @rich-iannone in our next meeting on timing 😅

**Comment by apoorvkh** [comment]
Great, thanks so much for the update!

**Comment by fzyzcjy** [comment]
+1 that would be super helpful!

**Comment by jrycw** [comment]
I'll close this issue as the feature has been implemented and merged.

**Comment by fzyzcjy** [comment]
Congratulations!

**Comment by aeturrell** [comment]
This is fantastic news, thank you for implementing. I will add to [Coding for Economists](https://aeturrell.github.io/coding-for-economists/intro.html) in due course! ([Issue here](https://github.com/aeturrell/coding-for-economists/issues/83))
