### ISSUE TITLE
when multiple styles specified in single tab_style call, only first is applied

### ISSUE THREAD

**Issue by machow** [posit-dev/great-tables#84]
It appears that when multiple styles are specified in a tab_style call, only the first appears.

```python
from great_tables import GT
from great_tables.data import airquality

gt_air = GT(airquality.head())

gt_air.tab_style(
    [style.fill("yellow"), style.borders(sides = "all")],
    loc.body("Temp", [1, 2])
)
```

<img width="858" alt="image" src="https://github.com/posit-dev/great-tables/assets/2574498/052e6f3f-f71a-47f4-9356-449a1b8e505a">

Note that if you switch the styles in the list around, it seems like only the first appears.

**Comment by rich-iannone** [comment]
Fixed by https://github.com/posit-dev/great-tables/pull/87.
