### ISSUE TITLE
When multiple locations specified in single tab_style called, only the last is applied

### ISSUE THREAD

**Issue by machow** [posit-dev/great-tables#85]
It looks like when tab_style gets a list of locations, only the last is applied to the data

```python
from great_tables import GT
from great_tables.data import airquality

gt_air = GT(airquality.head())
gt_air.tab_style(
    style.fill("yellow"),
    [loc.body("Temp", [1, 2]), loc.body("Ozone", [0])]
)
```

<img width="804" alt="image" src="https://github.com/posit-dev/great-tables/assets/2574498/afd43985-0bf7-430e-b2f2-97452ace1158">

**Comment by rich-iannone** [comment]
Fixed by https://github.com/posit-dev/great-tables/pull/87.
