### ISSUE TITLE
Using row ID values in `rows` is inconsistent when the table has row groups

### ISSUE THREAD

**Issue by rich-iannone** [posit-dev/great-tables#98]
When the table has row groups, rows tend to lose their original ordering due to migration of rows to the different groups. This makes using a row index value in a `rows` argument less recommended (you have to know the pre-shuffled index). Using the row ID is the recommended way, however, this fails and it seems that the row ID maps to the wrong row. Here is an example of that using `tab_style()`:

```py
from great_tables import GT, md, style, loc
from great_tables.data import towny

towny_mini = towny[["name", "website", "land_area_km2", "csd_type"]].tail(4)

(
    GT(towny_mini, rowname_col="name", groupname_col="csd_type")
    .tab_style(
        style=style.fill(color="Beige"),
        locations=loc.body(columns="land_area_km2", rows=["Woodstock"]),
    )
)
```

**Comment by machow** [comment]
From pairing, it sounds like the row ID should always be the original position (as passed into GT)

**Comment by rich-iannone** [comment]
This was partially fixed by @machow  in https://github.com/posit-dev/great-tables/pull/202. However, I'm seeing that the Pandas table behaves incorrectly compared to a Polars one. What follows is a pair of examples that involves a GT table having a stub and row groups, and, some basic styling.

Let's take a portion of the `towny` dataset as a Pandas DataFrame. From the output we see that 'Woodstock' is the sole city under the `csd_type` column: 

```python
from great_tables import GT, md, style, loc
from great_tables.data import towny
import polars as pl

towny_mini = towny[["name", "website", "land_area_km2", "csd_type"]].tail(4)

towny_mini
```

<img width="667" alt="pandas-output" src="https://github.com/posit-dev/great-tables/assets/5612024/22283722-8c83-463a-8f3b-b2dc37586b66">

Let's write the GT statement for this Pandas DF; notice that 'Woolwich' is in the 'city' group.

```python
# With Pandas -- incorrectly classifies Woolwich as a city; styling the 'Woodstock' row is also incorrect
(
    GT(towny_mini, rowname_col="name", groupname_col="csd_type")
    .tab_style(
        style=style.fill(color="Beige"),
        locations=loc.body(columns="land_area_km2", rows="Woodstock"),
    )
)
```

<img width="775" alt="pandas-GT" src="https://github.com/posit-dev/great-tables/assets/5612024/d73a8fc7-cb9a-4d3b-ba8a-38b186ee2689">

With a Polars DF, everything is correct:

```python
# With Polars -- correctly uses Woodstock in the city grouping and
#   styling is fine using the `rows=` reference
towny_mini_pl = pl.from_pandas(towny_mini)

(
    GT(towny_mini_pl, rowname_col="name", groupname_col="csd_type")
    .tab_style(
        style=style.fill(color="Beige"),
        locations=loc.body(columns="land_area_km2", rows="Woodstock"),
    )
)
```

<img width="775" alt="polars-GT" src="https://github.com/posit-dev/great-tables/assets/5612024/cc1149bd-1066-43e0-a62e-5f23e59f3cb6">
